# Generated by Django 6.1 on 2026-08-22 15:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generateddocument',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='githubrepository',
            options={'verbose_name_plural': 'GitHub repositories'},
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='format',
            field=models.CharField(choices=[('markdown', 'Markdown'), ('html', 'Html')], default='markdown', max_length=50),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='mcp_manager.githubrepository'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='githubrepository',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_owner_name'),
        ),
    ]
